Revert "[BZ-1072679] manage NoClassDefFoundError as a ClassNotFoundException raising a compilation error when it occurs"
This reverts commit c7973a93c64aa14b8741f94f5fc49d40ca69b0c8.